### ISSUE TITLE
How to mock?

### ISSUE THREAD

**Issue by Fighter19** [bromix/plugin.video.rtl2-now.de#5]
So, I was interested in how this plugin works exactly and I saw there was an interactive mode but I have no idea how to use it yet.

Nochmal auf Deutsch:
Also ich hab' gesehen dass es möglich sein sollte das Plugin von der Konsole aus zu debuggen. Nur irgendwie werde ich durch das ansehen des Codes nicht schlau wie man es öffnet.

**Comment by bromix** [comment]
No, no interactive mode...the mock is for the test-cases. Something you should implement if you're working with an interpreter language.

There is (and will) no console client to work with the mock. Look into the test-cases and start (debug) them ;)
I only work with definitive test-cases, otherwise it's wasted time ;)

**Comment by Fighter19** [comment]
That means if you want to debug you have to do that in XBMC?
Das heißt, wenn man etwas debuggen möchte, muss man dies innerhalb von XBMC machen?

Through an external Python debugger or how?
Durch einen externen Python debugger oder wie?

**Comment by bromix** [comment]
No, I run a test-case.
